### ISSUE TITLE
Provide UI to control speed of highlight animation

### ISSUE THREAD

**Issue by megahirt** [sillsdev/bible-karaoke#15]
The user needs to be able to control the speed of the highlight animation, for example how long it stays on the word.  The general feedback from users is that it is too "fast" or "chunky".  The highlight needs to stay on the word longer and fade away smoother I believe.

**Comment by kklcclkk** [comment]
Yes. Not only fade away smoother, but fade away more slowly, so there is more of a "trail" behind the current word that has the brightest highlighting.

One other related idea our team had, which I am not sure if you want to put this as a separate issue or not, @megahirt, is that instead of fading away, the highlighting would remain steady on every highlighted word in a sentence. The only animation the viewer/listener/karaoke-r would see is the word that is immediately being spoken becoming highlighted. By the end of the sentence, the entire sentence has become highlighted. Then the highlighting disappears, and it starts afresh with the first word of the next sentence, and so forth.
This is more like the kind of procedure they are accustomed to seeing in song karaoke, so it is more familiar and accessible. 
Please let me know if you need more explanation or examples as to what this would look like. I believe I sent you an example file previously that I made using a free karaoke software that used this  kind of highlighting technique.
I think the users would prefer this proposed type of highlighting over the current technique, but making the highlight fading slower and smoother could potentially make them less adamant about suggesting this. The fact that it is already a locally and popularly recognized karaoke style does make it attractive though.
They also pointed out that adding this feature would eliminate the need for the "Speech Bubble" box.

**Comment by jamesduncan** [comment]
We decided to change the animation to the traditional karaoke animation where the highlight builds on itself until the end of the line. This change is pretty straight forward and didn't need to tough any of the desktop app's UI controls.

**Comment by megahirt** [comment]
This change is in PR #35
