### ISSUE TITLE
Display estimated conversion time

### ISSUE THREAD

**Issue by grahammcculloch** [sillsdev/bible-karaoke#4]
From Lisa:

> After the user clicks "Make My Video," I think it would be helpful to have a message that helps the user understand approximately how long it will take. I know this is variable depending on the hardware on the person's machine, but for local, not so computer-savvy users, they need some indication that it will take more than 3 seconds. Maybe something like, "Please wait, this will take 5-10 minutes, depending on your computer" (or whatever you estimate it to take).

**Comment by megahirt** [comment]
I suspect that this is a non-issue once she and the other users see the progress bar as designed.  Her email indicated that she waited 25 minutes and the status message still read "getting things started".  She didn't ever get to the point of a progress bar after 25 minutes.

On the other hand you could show a progress bar immediately, and creep it along at 1% every 30 seconds until you have actual estimated progress, then might be an improvement.

**Comment by kklcclkk** [comment]
I think it would still be a helpful feature to have a time estimate, especially since the average user of this program may not have video rendering experience and may not realize that it will take a lot longer than they might expect.
If a time estimate is not possible, I would perhaps suggest some other message that would indicate to the user that it might take what might seem like a long time to them.
