### ISSUE TITLE
Dealing with no chapter announcement

### ISSUE THREAD

**Issue by kklcclkk** [sillsdev/bible-karaoke#41]
When I make the Ephesians 1 video, there is no chapter announcement in the audio, and so the highlighting animation is all off by a whole paragraph/sentence from the get-go.
For Colossians, there is a chapter announcement, so there is no problem.

**Comment by Hiro-Nakamura** [comment]
I think this is what we were fixing in issue #38?  Right?

**Comment by jamesduncan** [comment]
There seems to be an extra audio file included in the Ephesians sample we pulled from drive. My guess is it is the last audio file... @kklcclkk  can you confirm that this audio file does not belong in the chapter?

https://drive.google.com/open?id=1ny7t2snMMxVrL7MxqpcUzKsB_Sle6reX

If that file is supposed to belong can you help us find which of the 25 audio files is the extra file...because it seems that audio 0.wav matches to the heading of chapter 2.

**Comment by jamesduncan** [comment]
Other odd things about chapter one is 3.wav and 16.wav have a males voice instead of the woman that reads the rest of the chapter.

**Comment by kklcclkk** [comment]
The man is announcing the section headings and the woman is reading the Bible

**Comment by jamesduncan** [comment]
I just got off a call with Lisa…she helped me see that the issue with https://github.com/sillsdev/bible-karaoke/issues/41 is that the last verse text is not included in the info.xml. My guess is this could be a bug with HearThis on chapters that have a chapter heading at the beginning but no audio that corresponds with the item in the XML. The first two chapters in Ephesians in the samples we were provided have this issue. Can you have someone at SIL take a look?

**Comment by irahopkinson** [comment]
I've emailed Tom and CCed James.

**Comment by tombogle** [comment]
I would probably need access to the project (or more information) to know for sure, but my guess is that this is not a _bug_ in HearThis. HearThis allows you to exclude data in certain fields, so you can decide whether to include or omit section heads and chapter announcements. (It is also possible to omit blocks ad-hoc, in which case HearThis will also omit the corresponding entries in the timings file.
I don't know how Bible Karaoke attempts the alignment. Does it use the HearThis timing files, or does it generate its own (using Aeneas or some similar approach)? Also, I'm not sure if BK is using the combined audio that HearThis generates or going after the individual clips in HearThis' internal storage (under **ProgramData**).
In any case, there is probably a difference between what HearThis is doing and the assumptions that Bible Karaoke makes about what text is present or how it is divided up in the timing file.
For example, if BK is expecting the chapter announcement and the section head to be recorded as a single clip or to have a single timing file entry to cover the two clips when they are combined, that assumption would not match what HearThis does. It is also possible that when the recordist made the recordings, they recorded both the chapter announcement and the section head as a single clip (by mistake) and then skipped recording of the section head. This would result in a combined recording that _sounds_ correct, but the timing files would not match.
I just tested two different chapters in a sample project I have here, one with a section head and one without, and the recordings and generated timing files appear to be in sync, and nothing is missing.

**Comment by megahirt** [comment]
@tombogle The project in question should be N*** Ephesians chapter 1 and 2 https://drive.google.com/drive/u/1/folders/1TYqn5QzEBA4STU6Y2vv52L4WEQnEkTaQ

I'll try and answer other questions below:

BK reads HearThis data from the project directory under ProgramData.  It does not use any exported files from HearThis.  After the BK user selects which HearThis chapter to produce, BK reads the info.xml file to get the scripture text.  It matches up the text with the audio using the line number I believe.

We couldn't actually see any timing information in the info.xml file.  We estimate average "speed" for the text phrase based upon the number of characters and the length of the audio file.

It would be good to understand from you @tombogle where HearThis stores timing information.  info.xml doesn't seem to have this information as it only has RecordingTime (timestamp of recording)

Thank you for helping us solve this issue!

**Comment by tombogle** [comment]
Listening to the clips, I think I know what happened. They recorded a total of 25 clips. The first one has the section head but not the chapter announcement. After that, all the clips are off by one, corresponding to the text of the preceding block.
I’m pretty sure I know [how this happened](https://community.scripture.software.sil.org/t/user-read-the-next-line-after-the-yellow-highlight-any-fixes/175/5). In previous versions* of HearThis, teams would sometimes accidentally read the non-highlighted text on the screen instead of (or in addition to) the highlighted text. This was most likely to happen with a chapter announcement and a section head together since they are both short and don’t necessarily look or feel like separate things and especially since the chapter number is presented in English. If the recordist did this, they could then go on through the rest of the chapter recording the verse below the highlighted verse, which would mean that all the clips would be shifted by one position and the last verse would be recorded in the file that should have contained the second-to-last verse. At that point, an astute recordist or project administrator might notice the problem since HearThis would not mark the chapter as complete, but they might not notice that.
In the current version of HearThis, there is an advanced setting (on the Interface tab) to enable a context menu command which will allow a project administrator to shift recorded clips forward or backward to correctly align them to the blocks. As always, the latest version can be obtained from the [Download page](https://software.sil.org/hearthis/download/) on the website.

* The current version of HearThis discourages the recordist from making this mistake by dimming the context during recording.

**Comment by megahirt** [comment]
@kklcclkk can you look into what @tombogle just wrote?

**Comment by tombogle** [comment]
Here's a spreadsheet with my analysis: https://docs.google.com/spreadsheets/d/124Xyz5KlUEnFDwoU6g6Z6-hbfqE2bvFIgEkljdU2mwg/edit?usp=sharing

**Comment by kklcclkk** [comment]
Okay, thank you Tom and Chris for figuring this out. I have used the Shift Clips tool and I think I've got their recording straightened out now. I uploaded the new recordings to Google Drive and I'll share those with Chris and James.

**Comment by tombogle** [comment]
I should have a new version of HearThis ready soon that will also fix up the info.xml file when clip-shifting.

**Comment by tombogle** [comment]
The new version of HearThis is now available. Note that the improvement to the clip-shifting feature will not help retroactively. Any clips already shifted will have an info.xml file that does not accurately reflect the situation. (If you wanted to you could shift them back to the way they were using the old version of HearThis, then install the new version and shift them back into their correct spots.)

**Comment by tombogle** [comment]
Another new version of HearThis is available now with a fix that should actually work.

**Comment by kklcclkk** [comment]
Great, thank you. 
So, just to make sure I proceed correctly...do I just install the new version and attempt again to re-shift them back to their correct spots, having already shifted them back to the incorrect spots using 2.1.4?

**Comment by kklcclkk** [comment]
I got the video for chapter 6 to come out correctly!
Now the only problem is that it has an older version of the text in Paratext rather than the current version, but that's a different issue.

**Comment by megahirt** [comment]
This could potentially crop up as a problem for other BK users.  However, at this time I think it's worth waiting before we put developer effort into trying to figure out if there is no chapter announcement and see if other projects are running into the same issue.

Closing as "user support provided."
