### ISSUE TITLE
0.3.3 Checkmark in UI step 2 turns green too soon

### ISSUE THREAD

**Issue by kklcclkk** [sillsdev/bible-karaoke#57]
This is an extremely minor issue, and possibly a matter of opinion. 
I noticed that the checkmarks on the right side of the UI seem to appear "checked" (turn green) a little too early for Step 2. For example, in the screen shot below you can see I finished step 1, and am working on step 2, but before I have even done anything in step 2, the check mark has already turned green.
I would expect it to turn green only after I push the "Next" button. But perhaps the designer intended it to mean "you are allowed to go on to the next step if you wish"?
Anyway, there is my view/understanding as a user.
Thanks!

![image](https://user-images.githubusercontent.com/61860910/80051275-fd76a100-8541-11ea-9f77-6f8498d21bdc.png)

**Comment by jamesduncan** [comment]
Yes the checkmark means that the settings are in a state that pass requirements to generate a video. I would like to remove the preview from the accordion soon and just place it to the right and always have it visible in the future because there should never be a time where you do not have a checkmark for those settings. And it would better use the screen space to not build the UI so narrow. What do you think.  Okay if we move forward with that change for a future release?

James Duncan

**Comment by kklcclkk** [comment]
That sounds fine to me

**Comment by nh758** [comment]
will not fix, changing ui
