### ISSUE TITLE
Highlighting animation lagging behind audio at the end of sentences

### ISSUE THREAD

**Issue by kklcclkk** [sillsdev/bible-karaoke#60]
I realize this is probably a more difficult request, but the translators pointed this out when they saw a sample video I created, and I think bringing the accuracy in this area up would have a really good payoff.

The highlighting lagging behind the audio is a lot more noticeable than audio lagging behind highlighting animation.

It is not the end of every sentence, so I can try to do a little more observation to see if I can identify a pattern. I do know that for most languages in the world, this one included, the ends of most sentences will have lower relative pitch, lower volume, and slower rate of speech. So those might be someplace to start (since I don't know what kind of algorithms you're using on your end).

**Comment by jamesduncan** [comment]
One of the things I am looking at now is trimming the blank audio at the beginning and the end of audio clips. If they are noticing the highlighting lagging behind it could be due to blank space at the end of an audio clip. While this isn't going to fix it 100% because we really are just using some simple math to guess at word lengths it does help in my initial test to get highlighting a little closer. Can you tell me which Book and Chapter from the samples we have (or provide me with another) that I can run my script on to see if it helps and I will send it back to you for verification?

Something we are discussing as well is giving the editor the ability to go in and manually fix some word timings after we auto generate them. The tool we would hopefully use gives you the ability to navigate form phrase to phrase and word to word easily and adjust the beginning and endings of the words all with keyboard commands (or mouse clicking and dragging). It would be time consuming but the results would be very precise.

The other option would be asking Bob from our last big hackathon to consider completing his algorithm to produce word timings. Or maybe asking the SIL guys if they can impart any wisdom on how to auto generate word timings from their experience.

**Comment by kklcclkk** [comment]
The video I just made was Colossians 1

**Comment by megahirt** [comment]
Our timing algorithm is simple and limited.  Future versions may include a more complex, and perhaps more accurate timing method.  For now, audio files that don't follow a predictable speed/pattern or have unexpected silence at the beginning or end of the file may result in the timing becoming out of sync.  This issue lets us know that the timing algorithm has problems for some files.  Let's keep talking.  For now, we will work toward adding an automatic silence trimmer that is part of #54   We will close this issue for now.
