### ISSUE TITLE
Notify user of use of Analytics

### ISSUE THREAD

**Issue by nh758** [sillsdev/bible-karaoke#84]

**Comment by grahammcculloch** [comment]
Added to ui v2.

The following alert is displayed once on start-up. We cache the fact that it has been displayed and actioned in localStorage so it will not be displayed again. If the user accepts, the `enableAnalytics` settings is set to `true`; otherwise it is set to `false`.
 
![image](https://user-images.githubusercontent.com/2925657/91692424-93c36f00-eb93-11ea-82da-0d86266f648c.png)
